#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flake8-polyfill
Version  : 1.0.2
Release  : 13
URL      : https://files.pythonhosted.org/packages/e6/67/1c26634a770db5c442e361311bee73cb3a177adb2eb3f7af8953cfd9f553/flake8-polyfill-1.0.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/e6/67/1c26634a770db5c442e361311bee73cb3a177adb2eb3f7af8953cfd9f553/flake8-polyfill-1.0.2.tar.gz
Summary  : Polyfill package for Flake8 plugins
Group    : Development/Tools
License  : MIT
Requires: flake8-polyfill-license = %{version}-%{release}
Requires: flake8-polyfill-python = %{version}-%{release}
Requires: flake8-polyfill-python3 = %{version}-%{release}
Requires: flake8
BuildRequires : buildreq-distutils3
BuildRequires : flake8

%description
Polyfill for Flake8 Plugins
        =============================
        
        ``flake8-polyfill`` is a package that provides some compatibility helpers for
        Flake8 plugins that intend to support Flake8 2.x and 3.x simultaneously.
        
        
        Installation
        ============

%package license
Summary: license components for the flake8-polyfill package.
Group: Default

%description license
license components for the flake8-polyfill package.


%package python
Summary: python components for the flake8-polyfill package.
Group: Default
Requires: flake8-polyfill-python3 = %{version}-%{release}

%description python
python components for the flake8-polyfill package.


%package python3
Summary: python3 components for the flake8-polyfill package.
Group: Default
Requires: python3-core
Provides: pypi(flake8_polyfill)
Requires: pypi(flake8)

%description python3
python3 components for the flake8-polyfill package.


%prep
%setup -q -n flake8-polyfill-1.0.2
cd %{_builddir}/flake8-polyfill-1.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583534678
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flake8-polyfill
cp %{_builddir}/flake8-polyfill-1.0.2/LICENSE %{buildroot}/usr/share/package-licenses/flake8-polyfill/0671410ae2fab9ad6a4780d795840208ab774f86
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flake8-polyfill/0671410ae2fab9ad6a4780d795840208ab774f86

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
