#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flake8-polyfill
Version  : 1.0.1
Release  : 4
URL      : http://pypi.debian.net/flake8-polyfill/flake8-polyfill-1.0.1.tar.gz
Source0  : http://pypi.debian.net/flake8-polyfill/flake8-polyfill-1.0.1.tar.gz
Summary  : Polyfill package for Flake8 plugins
Group    : Development/Tools
License  : MIT
Requires: flake8-polyfill-python3
Requires: flake8-polyfill-license
Requires: flake8-polyfill-python
Requires: flake8
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Polyfill for Flake8 Plugins
        =============================
        
        ``flake8-polyfill`` is a package that provides some compatibility helpers for
        Flake8 plugins that intend to support Flake8 2.x and 3.x simultaneously.
        
        
        Installation
        ============

%package license
Summary: license components for the flake8-polyfill package.
Group: Default

%description license
license components for the flake8-polyfill package.


%package python
Summary: python components for the flake8-polyfill package.
Group: Default
Requires: flake8-polyfill-python3

%description python
python components for the flake8-polyfill package.


%package python3
Summary: python3 components for the flake8-polyfill package.
Group: Default
Requires: python3-core

%description python3
python3 components for the flake8-polyfill package.


%prep
%setup -q -n flake8-polyfill-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532218276
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/flake8-polyfill
cp LICENSE %{buildroot}/usr/share/doc/flake8-polyfill/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/flake8-polyfill/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
